const hard = {
  examiner: "imtihonchi",
  excitement: "hayajon",
  firefighter: "o't o'chiruvchi",
  flavour: "lazzat",
  guide: "qo'llanma",
  grateful: "minndatdor",
  handkerchief: "ro'molcha",
  honest: "halol",
  independent: "mustaqil",
  importance: "ahamiyatli",
  judge: "hakam",
  ladder: "narvon",
  leisure: "dam olish",
  luggage: "bagaj",
  microwave: "mikroto'lqinli pech",
  miserable: "baxtsiz",
  nearby: "yaqin",
  niece: "jiyan",
  occupation: "kasb",
  outdoor: "tashqarida",
  obviously: "aniq",
  pattern: "naqsh",
  pence: "pens",
  professor: "professor",
  site: "sayt",
  steak: "biftek",
  terrific: "ajoyib",
  unless: "agar",
  wardrobe: "shkaf",
};
