const medium = {
  alive: "tirik",
  aloud: "baland ovozda",
  already: "aallaqachon",
  allow: "ruhsat berish",
  achieve: "erishish",
  amazing: "ajoyib",
  afford: "imkon",
  blame: "ayb",
  belong: "tegishli",
  benefit: "zarba",
  blow: "jasur",
  brake: "tormoz",
  brave: "to'plam",
  bunch: "zerikkan",
  bored: "zerikkan",
  century: "asr",
  careful: "ehtiyot bo'ling",
  celebrate: "nishnlash",
  cancel: "bekor qilish",
  challenge: "qiyinchilik",
  chain: "zanjir",
  chapter: "bob",
  castle: "qal'a",
  dangerous: "xavfli",
  delivery: "yetkazish",
  direction: "yo'nalish",
  disappear: "g'aroyib",
  describe: "tasvirlamoq",
  enemy: "dushman",
  entrance: "kirish",
  expedition: "ekspeditsiya",
  effect: "ta'sir",
  excellent: "a'lo",
  exchange: "almashmoq",
  follow: "kuzatmoq",
  fog: "tuman",
  further: "yama",
  generation: "avlod",
  gentle: "yumshoq",
};
